INSERT INTO order_table(id,ITEM_NAME,COST,	ORDER_PLACED_TIME,STATUS)
    VALUES (101,'dal',150,CURRENT_TIMESTAMP,'PLACED');

INSERT INTO order_table(id,ITEM_NAME,COST,	ORDER_PLACED_TIME ,STATUS)
VALUES (102,'bread',150,CURRENT_TIMESTAMP,'PLACED');

INSERT INTO order_table(id,ITEM_NAME,COST,ORDER_PLACED_TIME,STATUS)
VALUES (103,'onion',150,CURRENT_TIMESTAMP,'PLACED');


INSERT INTO delivery_person(id,name,active)
VALUES (1,'DEL_BOY_1','1');

INSERT INTO delivery_person(id,name,active)
VALUES (2,'DEL_BOY_2','1');

INSERT INTO delivery_person(id,name,active)
VALUES (3,'DEL_BOY_3','1');


